sudo: required

services:
  - docker

language: generic

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build . -t giusedroid/drone-serverless;
    docker push giusedroid/drone-serverless;
    fi